version: '3.8'

services:
  redis-node1:
    image: redis:7
    container_name: redis-node1
    ports:
      - "7001:6379"
      - "17001:17001"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf", "--cluster-announce-port", "6379", "--cluster-announce-bus-port", "16379"]
    networks:
      - redis-cluster-networks

  redis-node2:
    image: redis:7
    container_name: redis-node2
    ports:
      - "7002:6379"
      - "17002:17001"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf", "--cluster-announce-port", "6379", "--cluster-announce-bus-port", "16379"]
    networks:
      - redis-cluster-networks
  
  redis-node3:
    image: redis:7
    container_name: redis-node3
    ports:
      - "7003:6379"
      - "17003:17001"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf", "--cluster-announce-port", "6379", "--cluster-announce-bus-port", "16379"]
    networks:
      - redis-cluster-networks

  redis-node4:
    image: redis:7
    container_name: redis-node4
    ports:
      - "7004:6379"
      - "17004:17001"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf", "--cluster-announce-port", "6379", "--cluster-announce-bus-port", "16379"]
    networks:
      - redis-cluster-networks
  
  redis-node5:
    image: redis:7
    container_name: redis-node5
    ports:
      - "7005:6379"
      - "17005:17001"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf", "--cluster-announce-port", "6379", "--cluster-announce-bus-port", "16379"]
    networks:
      - redis-cluster-networks
  
  redis-node6:
    image: redis:7
    container_name: redis-node6
    ports:
      - "7006:6379"
      - "17006:17001"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf", "--cluster-announce-port", "6379", "--cluster-announce-bus-port", "16379"]
    networks:
      - redis-cluster-networks

networks:
  redis-cluster-networks:
    driver: bridge