services:
  redis-master:
    image: redis:7
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./master.conf:/etc/redis/master.conf
    command: ["redis-server", "/etc/redis/master.conf"]

  redis-slave1:
    image: redis:7
    container_name: redis-slave1
    ports:
      - "6380:6379"
    volumes:
      - ./slave.conf:/etc/redis/slave.conf
    command: ["redis-server", "/etc/redis/slave.conf"]
    depends_on:
      - redis-master

  redis-slave2:
    image: redis:7
    container_name: redis-slave2
    ports:
      - "6381:6379"
    volumes:
      - ./slave.conf:/etc/redis/slave.conf
    command: ["redis-server", "/etc/redis/slave.conf"]
    depends_on:
      - redis-master

  sentinel1:
    image: redis:7
    container_name: sentinel1
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    command: ["redis-server", "/etc/redis/sentinel.conf", "--sentinel"]
    depends_on:
      - redis-master

  sentinel2:
    image: redis:7
    container_name: sentinel2
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    command: ["redis-server", "/etc/redis/sentinel.conf", "--sentinel"]
    depends_on:
      - redis-master

  sentinel3:
    image: redis:7
    container_name: sentinel3
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    command: ["redis-server", "/etc/redis/sentinel.conf", "--sentinel"]
    depends_on:
      - redis-master
