version: '3.9'

services:
  redis-master:
    image: redis:7
    container_name: redis-master
    command: ["redis-server", "/etc/redis/master.conf"]
    volumes:
      - "./master.conf:/etc/redis/master.conf"
    ports:
      - "6379:6379"
    networks:
      - redis-net
  
  redis-slave1:
    image: redis:7
    container_name: redis-slave1
    command: ["redis-server", "/etc/redis/slave.conf"]
    volumes:
      - "./slave.conf:/etc/redis/slave.conf"
    ports:
      - "6380:6379"
    networks:
      - redis-net

  redis-slave2:
    image: redis:7
    container_name: redis-slave2
    command: ["redis-server", "/etc/redis/slave.conf"]
    volumes:
      - "./slave.conf:/etc/redis/slave.conf"
    ports:
      - "6381:6379"
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge